#!/usr/bin/env python
"""EXPERIMENT (offline, proposal only -- no live rank.py change).

nflprops/rank.py's `penalty` term subtracts five hand-set weights from the
blend score: Doubtful/Out (0.60), dnp>25% (0.04), abs_spread>9 (0.02), thin
history n_games<6 (0.10), changed_team (0.06). Only the sixth, Questionable
(0.08), is cited to a measured number (44.1% vs 52.1% implied, decisions.md
#-- alternate-line finding). This refits the other five against actual 2025
outcomes.

DATA. reports/validate_reliability.csv (777 legs, 2025 weeks 6/10/14,
FanDuel alternate props, regenerated by scripts/validate_reliability.py from
data/hist/ -- already cached locally, no new API calls here). This is the
ONLY season with historical odds on disk: data/hist/ holds 2025 and 2026
snapshots only (checked directly), so 2019-2024 are not available for this
refit and are not used. 2026 rows are excluded explicitly below even though
none exist in this file, as a hard guard.

METHOD. For each of the five flags, compare hit rate for legs carrying it vs
legs that don't, via 5-fold cross-validation (GroupKFold by player_key, so
the same player's legs never span train/test -- a plain player generalizes
its own history within a fold otherwise). "Fitted value" = the out-of-fold
hit-rate shortfall (implied - actual) for legs carrying the flag, i.e. the
same units and sign convention as the current hand-set penalty. If a fold or
the whole flag has too few legs to trust (n<20 flagged legs pooled across all
folds, or a fold with 0 in either group), that weight is reported as
UNRELIABLE rather than as a number.

Read-only. Writes only data/penalty_refit_2025.csv. No API calls, no 2026.
"""
import pathlib
import sys

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from nflprops import reliability as R  # noqa: E402

SRC = ROOT / "reports" / "validate_reliability.csv"
OUT = ROOT / "data" / "penalty_refit_2025.csv"

# Current hand-set weights, from nflprops/rank.py (unchanged there).
CURRENT = {
    "doubtful_or_out": 0.60,
    "dnp_gt_25pct": 0.04,
    "abs_spread_gt_9": 0.02,
    "thin_history_lt6": 0.10,
    "changed_team": 0.06,
}
MIN_FLAGGED_N = 20  # below this, a fold-averaged rate is noise, not a weight


def load_legs():
    if not SRC.exists():
        raise SystemExit(f"missing {SRC} -- run scripts/validate_reliability.py first "
                          f"(it hits data/hist/'s cache, no new API calls expected)")
    df = pd.read_csv(SRC)
    df = df[df.season == 2025]  # hard guard, even though this file has no other season
    return df


def attach_risk_features(df):
    """Bring in report_status, abs_spread, changed_team per (season, week,
    player_key) -- same source functions rank.py uses live, called once per
    of the three weeks in this file."""
    out = []
    for wk, g in df.groupby("week"):
        hist = R._history(2025, wk, R.DEFAULT_LOOKBACK)
        tm = hist[["player_key", "team"]].drop_duplicates("player_key")
        inj, sp = R.risk_flags(2025, wk)
        cont = R.role_continuity(2025, wk)

        g = g.merge(tm, on="player_key", how="left")
        g = g.merge(sp.drop_duplicates("team")[["team", "abs_spread"]], on="team", how="left")
        g = g.merge(inj[["player_key", "report_status"]].drop_duplicates("player_key"),
                     on="player_key", how="left")
        g = g.merge(cont[["player_key", "changed_team"]].drop_duplicates("player_key"),
                     on="player_key", how="left")
        out.append(g)
    df = pd.concat(out, ignore_index=True)
    df["changed_team"] = df.changed_team.fillna(False)

    df["flag_doubtful_or_out"] = df.report_status.isin(["Doubtful", "Out"])
    df["flag_dnp_gt_25pct"] = df.dnp.fillna(0) > 0.25
    df["flag_abs_spread_gt_9"] = df.abs_spread.fillna(0) > 9
    df["flag_thin_history_lt6"] = df.n_games.fillna(0) < 6
    df["flag_changed_team"] = df.changed_team
    return df


def cv_shortfall(df, flag_col, n_folds=5):
    """Out-of-fold (implied - actual) for legs carrying the flag, grouped by
    player so no player crosses a fold boundary. Returns (mean_shortfall,
    n_flagged_scored, per_fold list) or (None, n, []) if too thin."""
    groups = df.player_key.astype("category").cat.codes
    n_groups = groups.nunique()
    k = min(n_folds, n_groups) if n_groups >= 2 else 0
    if k < 2:
        return None, int(df[flag_col].sum()), []

    gkf = GroupKFold(n_splits=k)
    fold_rows = []
    for _, test_idx in gkf.split(df, groups=groups):
        te = df.iloc[test_idx]
        flagged = te[te[flag_col]]
        if len(flagged) == 0:
            continue
        implied = flagged.fair.mean()
        actual = flagged.won.mean()
        fold_rows.append(dict(n=len(flagged), implied=implied, actual=actual,
                              shortfall=implied - actual))

    n_total_flagged = int(df[flag_col].sum())
    if n_total_flagged < MIN_FLAGGED_N or not fold_rows:
        return None, n_total_flagged, fold_rows

    n_tot = sum(r["n"] for r in fold_rows)
    mean_shortfall = sum(r["shortfall"] * r["n"] for r in fold_rows) / n_tot
    return mean_shortfall, n_total_flagged, fold_rows


def main():
    df = load_legs()
    df = attach_risk_features(df)
    print(f"{len(df)} legs, 2025 weeks {sorted(df.week.unique())}\n")

    rows = []
    for key, flag_col in [
        ("doubtful_or_out", "flag_doubtful_or_out"),
        ("dnp_gt_25pct", "flag_dnp_gt_25pct"),
        ("abs_spread_gt_9", "flag_abs_spread_gt_9"),
        ("thin_history_lt6", "flag_thin_history_lt6"),
        ("changed_team", "flag_changed_team"),
    ]:
        shortfall, n_flagged, folds = cv_shortfall(df, flag_col)
        current = CURRENT[key]
        if shortfall is None:
            print(f"{key:<20} n_flagged={n_flagged:<4}  UNRELIABLE (< {MIN_FLAGGED_N} "
                  f"flagged legs pooled or too few groups) -- current weight {current} kept as-is")
            rows.append(dict(penalty=key, n_flagged=n_flagged, current_weight=current,
                             fitted_weight=None, reliable=False, oof_hit_rate_current=None))
            continue
        print(f"{key:<20} n_flagged={n_flagged:<4}  current={current:.3f}  "
              f"fitted={shortfall:+.3f}  ({len(folds)} folds)")
        rows.append(dict(penalty=key, n_flagged=n_flagged, current_weight=current,
                         fitted_weight=round(float(shortfall), 4), reliable=True))

    res = pd.DataFrame(rows)
    res.to_csv(OUT, index=False)

    print(f"\nUnflagged baseline: n={int((~df[[c for c in df.columns if c.startswith('flag_')]].any(axis=1)).sum())}  "
          f"implied {df[~df[[c for c in df.columns if c.startswith('flag_')]].any(axis=1)].fair.mean()*100:.1f}%  "
          f"actual {df[~df[[c for c in df.columns if c.startswith('flag_')]].any(axis=1)].won.mean()*100:.1f}%")
    print(f"\nwritten -> {OUT}")


if __name__ == "__main__":
    main()
